### ISSUE TITLE
I have 2 listings for HTML tidy in my preferences menu

### ISSUE THREAD

**Issue by smlombardi** [welovewordpress/SublimeHtmlTidy#25]
Why, and how should I fix?  See: 

 ![screen](https://img.skitch.com/20121015-piybh5qj21q18bkxuxr4ux38u3.jpg)

**Comment by aaronmw** [comment]
Same here...

**Comment by nnthnn** [comment]
To fix the problem: Open your Packages directory (`Preferences >> Browse Packages ...`), open the `HtmlTidy` directory and delete any `welovewordpress-htmltidy-*` folders you see there.

The problem is that Package Control could not correctly update this package, and left the newer version inside. Next time you close all your Sublime Text instances, Package Control will correctly update the package.
