### ISSUE TITLE
Remove prefix

### ISSUE THREAD

**Issue by sindresorhus** [welovewordpress/SublimeHtmlTidy#4]
I don't understand why you've prefixed every option with `htmltidy`. Every html tidy option is in the `HtmlTidy.sublime-settings` folder, so there is no chance of name collision.

**Comment by welovewordpress** [comment]
You're completely right. The prefix was left over from a former version, where I hadn't decided to put them in its own settings file.

I removed the prefix now and tried my best to include an update message, but I don't know of this works with Package Control. (I don't have custom version numbers (yet), so I wonder if the update message will fire for 2012.03.20.05.10.1 and similar)

Sorry if this breaks your current user settings - but better now than later...

**Comment by aaronmw** [comment]
You may have removed the prefix, but unless I use the prefix, the settings I change are ignored. That is, setting:

"indent-attributes": false

Will still cause attributes to be indented. But this fixes it:

"htmltidy-indent-attributes": false

So yeah. That's a pretty insane bug :P It's impossible to configure because options I change in the settings file do nothing at all unless I rename the options to include the prefix...

**Comment by welovewordpress** [comment]
It's fixed now. Thanks for pointing it out.
